// <auto-generated />
using System;
using Maktabaty.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Maktabaty.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260506180318_ModifiedBookstable")]
    partial class ModifiedBookstable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Maktabaty.Domain.Entities.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "George R. R. Martin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "J.K. Rowling"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Stephen King"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Isaac Asimov"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Philip K. Dick"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Agatha Christie"
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Jane Austen"
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Charles Dickens"
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Leo Tolstoy"
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Dan Brown"
                        });
                });

            modelBuilder.Entity("Maktabaty.Domain.Entities.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Hall")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailableForRental")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("PublishingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Description = "The first novel in A Song of Ice and Fire, introducing the struggle for the Iron Throne in Westeros.",
                            Hall = "A1",
                            ImageUrl = "https://covers.openlibrary.org/b/isbn/9780553103540-L.jpg",
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            Publisher = "Bantam Spectra",
                            PublishingDate = new DateTime(1996, 8, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "A Game of Thrones",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Description = "The Seven Kingdoms fracture as rival kings clash, while the threat beyond the Wall grows.",
                            Hall = "A1",
                            ImageUrl = "https://covers.openlibrary.org/b/isbn/9780553108033-L.jpg",
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            Publisher = "Bantam Spectra",
                            PublishingDate = new DateTime(1998, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "A Clash of Kings",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            Description = "Harry discovers he is a wizard and begins his first year at Hogwarts School of Witchcraft and Wizardry.",
                            Hall = "B2",
                            ImageUrl = "https://covers.openlibrary.org/b/isbn/9780747532699-L.jpg",
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            Publisher = "Bloomsbury",
                            PublishingDate = new DateTime(1997, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Harry Potter and the Philosopher's Stone",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            Description = "A mysterious force petrifies students at Hogwarts, and Harry uncovers a hidden chamber.",
                            Hall = "B2",
                            ImageUrl = "https://covers.openlibrary.org/b/isbn/9780747538493-L.jpg",
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            Publisher = "Bloomsbury",
                            PublishingDate = new DateTime(1998, 7, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Harry Potter and the Chamber of Secrets",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            Description = "A family becomes caretakers of an isolated hotel where supernatural forces drive the father toward madness.",
                            Hall = "C3",
                            ImageUrl = "https://covers.openlibrary.org/b/isbn/9780385121675-L.jpg",
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            Publisher = "Doubleday",
                            PublishingDate = new DateTime(1977, 1, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "The Shining",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            Description = "In Derry, Maine, a group of friends confronts a shape-shifting evil that resurfaces every 27 years.",
                            Hall = "C3",
                            ImageUrl = "https://covers.openlibrary.org/b/isbn/9780670813025-L.jpg",
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            Publisher = "Viking",
                            PublishingDate = new DateTime(1986, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "It",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 4,
                            Description = "Hari Seldon creates the Foundation to preserve knowledge as the Galactic Empire falls.",
                            Hall = "D4",
                            ImageUrl = "https://covers.openlibrary.org/b/isbn/9780553293357-L.jpg",
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            Publisher = "Gnome Press",
                            PublishingDate = new DateTime(1951, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Foundation",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 4,
                            Description = "A collection of stories that introduced the Three Laws of Robotics.",
                            Hall = "D4",
                            ImageUrl = "https://covers.openlibrary.org/b/isbn/9780553382563-L.jpg",
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            Publisher = "Gnome Press",
                            PublishingDate = new DateTime(1950, 12, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "I, Robot",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 5,
                            Description = "In a post-apocalyptic future, bounty hunter Rick Deckard tracks rogue androids.",
                            Hall = "D4",
                            ImageUrl = "https://covers.openlibrary.org/b/isbn/9780345404473-L.jpg",
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            Publisher = "Doubleday",
                            PublishingDate = new DateTime(1968, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Do Androids Dream of Electric Sheep?",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 5,
                            Description = "An alternate history where the Axis powers won World War II and divided the United States.",
                            Hall = "D4",
                            ImageUrl = "https://covers.openlibrary.org/b/isbn/9780547572482-L.jpg",
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            Publisher = "Putnam",
                            PublishingDate = new DateTime(1962, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "The Man in the High Castle",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 6,
                            Description = "Detective Hercule Poirot investigates a murder aboard the famous train.",
                            Hall = "E5",
                            ImageUrl = "https://covers.openlibrary.org/b/isbn/9780062693662-L.jpg",
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            Publisher = "Collins Crime Club",
                            PublishingDate = new DateTime(1934, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Murder on the Orient Express",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 6,
                            Description = "Ten strangers on an isolated island are accused of crimes and eliminated one by one.",
                            Hall = "E5",
                            ImageUrl = "https://covers.openlibrary.org/b/isbn/9780062073488-L.jpg",
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            Publisher = "Collins Crime Club",
                            PublishingDate = new DateTime(1939, 11, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "And Then There Were None",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 7,
                            Description = "Elizabeth Bennet navigates manners, upbringing, and marriage in Regency England.",
                            Hall = "F6",
                            ImageUrl = "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            Publisher = "T. Egerton",
                            PublishingDate = new DateTime(1813, 1, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Pride and Prejudice",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 7,
                            Description = "The Dashwood sisters cope with love, loss, and society after a change in fortune.",
                            Hall = "F6",
                            ImageUrl = "https://covers.openlibrary.org/b/isbn/9780141439662-L.jpg",
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            Publisher = "Thomas Egerton",
                            PublishingDate = new DateTime(1811, 10, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Sense and Sensibility",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 8,
                            Description = "Pip's coming-of-age story unfolds with ambition, love, and the consequences of secrets.",
                            Hall = "G7",
                            ImageUrl = "https://covers.openlibrary.org/b/isbn/9780141439563-L.jpg",
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            Publisher = "Chapman & Hall",
                            PublishingDate = new DateTime(1861, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Great Expectations",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 8,
                            Description = "A sweeping historical novel set in London and Paris during the French Revolution.",
                            Hall = "G7",
                            ImageUrl = "https://covers.openlibrary.org/b/isbn/9780141439600-L.jpg",
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            Publisher = "Chapman & Hall",
                            PublishingDate = new DateTime(1859, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "A Tale of Two Cities",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 9,
                            Description = "An epic portrayal of Russian society during the Napoleonic Wars.",
                            Hall = "H8",
                            ImageUrl = "https://covers.openlibrary.org/b/isbn/9780140447934-L.jpg",
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            Publisher = "The Russian Messenger",
                            PublishingDate = new DateTime(1869, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "War and Peace",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 9,
                            Description = "A tragic story of love, society, and morality in imperial Russia.",
                            Hall = "H8",
                            ImageUrl = "https://covers.openlibrary.org/b/isbn/9780143035008-L.jpg",
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            Publisher = "The Russian Messenger",
                            PublishingDate = new DateTime(1878, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Anna Karenina",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 10,
                            Description = "Symbologist Robert Langdon unravels a mystery that spans art, history, and secret societies.",
                            Hall = "I9",
                            ImageUrl = "https://covers.openlibrary.org/b/isbn/9780385504201-L.jpg",
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            Publisher = "Doubleday",
                            PublishingDate = new DateTime(2003, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "The Da Vinci Code",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 10,
                            Description = "Robert Langdon investigates a conspiracy involving the Illuminati and the Vatican.",
                            Hall = "I9",
                            ImageUrl = "https://covers.openlibrary.org/b/isbn/9780671027360-L.jpg",
                            IsAvailableForRental = true,
                            IsDeleted = false,
                            Publisher = "Pocket Books",
                            PublishingDate = new DateTime(2000, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Angels & Demons",
                            UpdatedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Maktabaty.Domain.Entities.Models.BookCategory", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BookCategories");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 2,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 3,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 4,
                            CategoryId = 3
                        },
                        new
                        {
                            BookId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 5,
                            CategoryId = 6
                        },
                        new
                        {
                            BookId = 5,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 6,
                            CategoryId = 6
                        },
                        new
                        {
                            BookId = 6,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 7,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 7,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 8,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 8,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 9,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 9,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 10,
                            CategoryId = 2
                        },
                        new
                        {
                            BookId = 10,
                            CategoryId = 7
                        },
                        new
                        {
                            BookId = 11,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 11,
                            CategoryId = 6
                        },
                        new
                        {
                            BookId = 12,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 12,
                            CategoryId = 6
                        },
                        new
                        {
                            BookId = 13,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 13,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 14,
                            CategoryId = 5
                        },
                        new
                        {
                            BookId = 14,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 15,
                            CategoryId = 7
                        },
                        new
                        {
                            BookId = 15,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 16,
                            CategoryId = 7
                        },
                        new
                        {
                            BookId = 16,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 17,
                            CategoryId = 7
                        },
                        new
                        {
                            BookId = 17,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 18,
                            CategoryId = 7
                        },
                        new
                        {
                            BookId = 18,
                            CategoryId = 1
                        },
                        new
                        {
                            BookId = 19,
                            CategoryId = 6
                        },
                        new
                        {
                            BookId = 19,
                            CategoryId = 4
                        },
                        new
                        {
                            BookId = 20,
                            CategoryId = 6
                        },
                        new
                        {
                            BookId = 20,
                            CategoryId = 4
                        });
                });

            modelBuilder.Entity("Maktabaty.Domain.Entities.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 6,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Thriller"
                        },
                        new
                        {
                            Id = 7,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Historical"
                        },
                        new
                        {
                            Id = 8,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            Id = 9,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 10,
                            CreatedOn = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Self-Help"
                        });
                });

            modelBuilder.Entity("Maktabaty.Domain.Entities.Models.Book", b =>
                {
                    b.HasOne("Maktabaty.Domain.Entities.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Maktabaty.Domain.Entities.Models.BookCategory", b =>
                {
                    b.HasOne("Maktabaty.Domain.Entities.Models.Book", "Book")
                        .WithMany("BookCategories")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maktabaty.Domain.Entities.Models.Category", "Category")
                        .WithMany("BookCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Maktabaty.Domain.Entities.Models.Book", b =>
                {
                    b.Navigation("BookCategories");
                });

            modelBuilder.Entity("Maktabaty.Domain.Entities.Models.Category", b =>
                {
                    b.Navigation("BookCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
